name: lmnasux
 
on:
  push:
     branches: [develop]


jobs: 
  lintTest:
     name: Lint
     runs-on: ubuntu-latest
     steps:
        -name: Clone Repository
         uses: actions/ceckout@v2
        -name: Install Dependencies
         run:
           echo "Running Installing Dependencies..."
           npm install
        -name: Run Linting
         run: |
           echo "Running Linting Tests.."
           npm run lint
         env:
           CI: true
           
   SecurityCheck:
     name: Security Check
     runs-on: ubuntu-latest
     steps:
       name: Check for Security
       runs: |
        echo "Running Security Checks.."
        sleep 5s;
        echo "Running Security Checks.. 1"
        sleep 5s;
        echo "Running Security Checks.. 2"
        sleep 5s;
        echo "Running Security Checks.. 3"
        sleep 5s;
          
